`timescale 1ns/1ps
// ============================================================
// Auto-generated by fsm_generator.py -- DO NOT EDIT
// Design : ddr4_bank_tRAS_fsm
// States : IDLE, COUNTING, DONE
// Reset  : rst_n (sync)
// Regenerate: python3 fsm_generator.py <spec>.yaml
// ============================================================

module ddr4_bank_tRAS_fsm (
    input  logic        clk,
    input  logic        rst_n,
    input  logic        start,
    input  logic        ack,
    output logic        tRAS_done
);

    // ---------------------------------------------------------
    // State type
    // ---------------------------------------------------------
    typedef enum logic [1:0] {
        IDLE                 = 2'd0,
        COUNTING             = 2'd1,
        DONE                 = 2'd2
    } state_t;

    state_t current_state, next_state;

    // ---------------------------------------------------------
    // Counters (auto-sized from transition conditions)
    // ---------------------------------------------------------
    logic [5:0] tRAS_counter;  // 6 bit(s), holds up to 63
    localparam int TRAS_COUNTER_WIDTH = $bits(tRAS_counter);
    localparam logic [TRAS_COUNTER_WIDTH-1:0] TRAS_COUNTER_ZERO_L = TRAS_COUNTER_WIDTH'(0);
    localparam logic [TRAS_COUNTER_WIDTH-1:0] TRAS_COUNTER_ONE_L = TRAS_COUNTER_WIDTH'(1);

    // ---------------------------------------------------------
    // State register  (sync reset)
    // ---------------------------------------------------------
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            current_state <= IDLE;
            tRAS_counter <= TRAS_COUNTER_ZERO_L;
        end else begin
            current_state <= next_state;
            // Reset counters on any state change;
            // increment only in the state the counter belongs to.
            if (current_state != next_state) begin
                tRAS_counter <= TRAS_COUNTER_ZERO_L;
            end else begin
                if (current_state == COUNTING) begin
                    tRAS_counter <= tRAS_counter + TRAS_COUNTER_ONE_L;
                end
            end
        end
    end

    // ---------------------------------------------------------
    // Next-state logic
    // ---------------------------------------------------------
    always_comb begin
        next_state = current_state;  // default: hold current state
        case (current_state)
            IDLE: if (start == 1'd1) next_state = COUNTING;
            COUNTING: if (tRAS_counter >= 6'd52) next_state = DONE;
            DONE: if (ack == 1'd1) next_state = IDLE;
            default: next_state = IDLE;  // illegal encoding -- recover to reset state
        endcase
    end

    // ---------------------------------------------------------
    // Output logic (Moore)
    // ---------------------------------------------------------
    always_comb begin
        tRAS_done = (current_state == DONE);
    end

endmodule  // ddr4_bank_tRAS_fsm
