#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=0

usage() {
    cat <<'EOF'
Usage: ./clear.sh [--dry-run]

Removes artifacts generated by:
  - ./start_flow.sh
  - ./run_sim.sh
  - python3 debug_agent.py ... debug/demo flows

Preserves source inputs, configs/user_input.yaml, jedec/, debug fixtures, and
debug layout .gitkeep files.
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --dry-run)
            DRY_RUN=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown flag: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

display_path() {
    local path="$1"
    printf '%s\n' "${path#$SCRIPT_DIR/}"
}

require_repo_path() {
    local path="$1"
    case "$path" in
        "$SCRIPT_DIR"/*)
            ;;
        *)
            echo "[CLEAR] Refusing path outside repo: $path" >&2
            exit 1
            ;;
    esac
}

remove_path() {
    local path="$1"
    require_repo_path "$path"

    if [ ! -e "$path" ] && [ ! -L "$path" ]; then
        echo "[CLEAR] skip missing: $(display_path "$path")"
        return 0
    fi

    if [ "$DRY_RUN" -eq 1 ]; then
        echo "[CLEAR] would remove: $(display_path "$path")"
        return 0
    fi

    rm -rf -- "$path"
    echo "[CLEAR] removed: $(display_path "$path")"
}

remove_matches() {
    local label="$1"
    shift

    if [ "$#" -eq 0 ]; then
        echo "[CLEAR] skip missing: $label"
        return 0
    fi

    local path
    for path in "$@"; do
        remove_path "$path"
    done
}

generated_dirs=(
    "$SCRIPT_DIR/rtl_output"
    "$SCRIPT_DIR/expanded"
    "$SCRIPT_DIR/inputs/generated"
    "$SCRIPT_DIR/tb"
    "$SCRIPT_DIR/obj_dir"
    "$SCRIPT_DIR/__pycache__"
    "$SCRIPT_DIR/.llm_cache"
)

generated_files=(
    "$SCRIPT_DIR/flow.log"
    "$SCRIPT_DIR/bist.log"
)

for path in "${generated_dirs[@]}" "${generated_files[@]}"; do
    remove_path "$path"
done

remove_matches "ir/*_ir.json" "$SCRIPT_DIR"/ir/*_ir.json
remove_matches "*.vcd" "$SCRIPT_DIR"/*.vcd
remove_matches "debug/failures/[0-9][0-9][0-9][0-9]_*" "$SCRIPT_DIR"/debug/failures/[0-9][0-9][0-9][0-9]_*

echo "[CLEAR] Done."
