design_name: ddr4_controller
profile:
  type: basic
memory:
  protocol: DDR4
  speed: '3200'
topology:
  banks: 4
features:
  scheduler: simple
  page_policy: open_page
  refresh: true
  tFAW: true
  tRRD: true
