`timescale 1ns/1ps
// ============================================================
// Auto-generated by generate_wrapper.py -- DO NOT EDIT
// Design : ddr4_controller_top
// Scheduler policy : simple
// Page policy      : open_page
// Bank count       : 4
// ============================================================

module ddr4_controller_top (
    input  logic clk,
    input  logic rst_n,
    input  logic txn_valid,
    input  logic txn_is_write,
    input  logic [3:0] txn_addr,
    input  logic [31:0] txn_wdata,
    input  logic [1:0] txn_bank,
    output logic cmd_ready,
    output logic rsp_valid,
    output logic [31:0] rsp_rdata
);

    localparam int BANK_COUNT = 4;
    localparam int ADDR_WIDTH = 4;
    localparam int DATA_WIDTH = 32;
    localparam int BANK_SEL_WIDTH = 2;
    localparam int MEM_DEPTH = 1 << ADDR_WIDTH;
    localparam int ROW_WIDTH = 2;
    localparam int COL_WIDTH = 2;
    localparam int HIT_SERVICE_CYCLES = 1;
    localparam int SLOW_SERVICE_CYCLES = 3;
    localparam int SERVICE_COUNTER_WIDTH = 2;
    localparam int REQ_QUEUE_DEPTH = 4;
    localparam int REQ_SEL_WIDTH = $clog2(REQ_QUEUE_DEPTH);
    localparam int SCHED_BANK_COUNT = 4;
    localparam bit KEEP_ROWS_OPEN = 1'b1;
    localparam logic [2:0] TFAW_ACT_LIMIT_MINUS_ONE = 3'd3;

    logic issue_ref;
    logic issue_txn;
    logic issue_valid;
    logic act_allowed;
    logic slow_path_allowed;
    logic act_pulse;
    logic accept_txn_fire;
    logic accept_txn;
    logic accepted_hit;
    logic accepted_slow;
    logic accepted_read;
    logic accepted_write;
    logic accept_txn_q;
    logic accepted_row_closed_q;
    logic accepted_row_hit_q;
    logic accepted_row_miss_q;
    logic [BANK_SEL_WIDTH-1:0] accepted_bank_q;
    logic [1:0] accepted_txn_cmd_type_q;
    logic [3:0] accepted_bank_cmd_valid_q;
    logic accepted_open_row_valid_q;
    logic [ROW_WIDTH-1:0] accepted_prev_open_row_q;
    logic [ROW_WIDTH-1:0] accepted_requested_row_q;
    logic [COL_WIDTH-1:0] accepted_requested_col_q;
    logic txn_sched_grant;
    logic controller_ready;
    logic downstream_cmd_ready;
    logic scheduler_timing_ok;
    logic service_done;
    logic service_pending_q;
    logic service_is_write_q;
    logic service_update_open_row_q;
    logic service_prev_row_valid_q;
    logic [1:0] txn_cmd_type;
    logic [BANK_SEL_WIDTH-1:0] service_bank_q;
    logic [ADDR_WIDTH-1:0] service_addr_q;
    logic [DATA_WIDTH-1:0] service_wdata_q;
    logic [ROW_WIDTH-1:0] requested_row;
    logic [COL_WIDTH-1:0] requested_col;
    logic selected_row_open_valid;
    logic [ROW_WIDTH-1:0] selected_open_row;
    logic incoming_row_open_valid;
    logic [ROW_WIDTH-1:0] incoming_open_row;
    logic incoming_row_hit;
    logic incoming_timing_ok;
    logic [ROW_WIDTH-1:0] service_row_q;
    logic [ROW_WIDTH-1:0] service_prev_row_q;
    logic [SERVICE_COUNTER_WIDTH-1:0] service_cycles_left_q;
    typedef struct packed {
        logic [1:0]  bank;
        logic [9:0]  row;
        logic [5:0]  col;
        logic        is_write;
        logic [31:0] wdata;
    } request_t;
    request_t decoded_req;
    request_t selected_req;
    request_t req_array [REQ_QUEUE_DEPTH];
    logic req_valid [REQ_QUEUE_DEPTH];
    logic [50:0] decoded_req_packed;
    logic [(REQ_QUEUE_DEPTH*51)-1:0] req_array_packed;
    logic [REQ_QUEUE_DEPTH-1:0] req_valid_packed;
    logic [REQ_SEL_WIDTH-1:0] sel_idx;
    logic deq_en;
    logic enq_ready;
    logic enqueue_req_valid;
    logic enqueue_fire;
    logic txn_enqueued_q;
    logic [17:0] decoded_addr;
    logic [1:0] selected_bank;
    logic [1:0] incoming_bank;
    logic [ADDR_WIDTH-1:0] selected_addr;
    logic rsp_valid_q;
    logic [DATA_WIDTH-1:0] rsp_rdata_q;
    logic [31:0] cnt_accept;
    logic [31:0] cnt_row_hit;
    logic [31:0] cnt_row_miss;
    logic [31:0] cnt_row_closed;
    logic [31:0] cnt_stall;
    logic [31:0] cnt_stall_busy;
    logic [31:0] cnt_stall_trrd;
    logic [31:0] cnt_stall_refresh;
    logic [31:0] cnt_stall_other;
    logic [31:0] cnt_latency_hit_total;
    logic [31:0] cnt_latency_nonhit_total;
    logic [31:0] cnt_latency_hit_count;
    logic [31:0] cnt_latency_nonhit_count;
    logic [31:0] cnt_accept_bank [0:BANK_COUNT-1];
    logic [31:0] cnt_row_hit_bank [0:BANK_COUNT-1];
    logic [31:0] cnt_row_miss_bank [0:BANK_COUNT-1];
    logic [31:0] cnt_row_closed_bank [0:BANK_COUNT-1];
    logic is_row_closed;
    logic is_row_hit;
    logic is_row_miss;
    logic row_replacement_event;
    logic [3:0] row_open_valid;
    logic [ROW_WIDTH-1:0] open_row [0:BANK_COUNT-1];
    logic [SCHED_BANK_COUNT-1:0] scheduler_bank_active;
    logic [9:0] scheduler_bank_open_row [0:SCHED_BANK_COUNT-1];
    logic [(SCHED_BANK_COUNT*10)-1:0] scheduler_bank_open_row_packed;
    logic [3:0] bank_cmd_valid;
    logic [3:0] bank_cmd_ready;
    logic [3:0] bank_bank_idle;
    logic [3:0] bank_bank_active;
    logic [3:0] bank_activating;
    logic [DATA_WIDTH-1:0] bank_mem [0:BANK_COUNT-1][0:MEM_DEPTH-1];
    integer bank_mem_bank;
    integer bank_mem_addr;
    logic [1:0] bank0_cmd_type;
    logic [1:0] bank1_cmd_type;
    logic [1:0] bank2_cmd_type;
    logic [1:0] bank3_cmd_type;
    logic ref_req;
    logic ref_ack;
    logic [2:0] tFAW_act_count;
    logic tFAW_block;
    logic tFAW_ok;
    logic tfaw_can_accept_act;
    logic tRRD_block;

    assign decoded_addr = 18'(txn_addr);
    assign decoded_req.bank = 2'(txn_bank);
    assign decoded_req.row = 10'(txn_addr[ADDR_WIDTH-1 -: ROW_WIDTH]);
    assign decoded_req.col = 6'(txn_addr[COL_WIDTH-1:0]);
    assign decoded_req.is_write = txn_is_write;
    assign decoded_req.wdata = txn_wdata;
    assign decoded_req_packed = decoded_req;
    assign selected_req = req_array[sel_idx];
    assign selected_bank = (BANK_COUNT == 1) ? 2'd0 :
                           (BANK_COUNT == 2) ? {1'b0, selected_req.bank[0]} :
                           selected_req.bank;
    assign incoming_bank = (BANK_COUNT == 1) ? 2'd0 :
                           (BANK_COUNT == 2) ? {1'b0, decoded_req.bank[0]} :
                           decoded_req.bank;
    assign selected_addr = ADDR_WIDTH'({selected_req.row[ROW_WIDTH-1:0], selected_req.col[COL_WIDTH-1:0]});
    assign requested_row = selected_req.row[ROW_WIDTH-1:0];
    assign requested_col = selected_req.col[COL_WIDTH-1:0];
    assign txn_cmd_type = selected_req.is_write ? 2'b10 : 2'b01;
    assign tfaw_can_accept_act = (tFAW_act_count < TFAW_ACT_LIMIT_MINUS_ONE);
    assign slow_path_allowed = tfaw_can_accept_act & ~tRRD_block;
    assign act_allowed = slow_path_allowed;
    assign is_row_closed = ~selected_row_open_valid;
    assign is_row_hit = selected_row_open_valid && (requested_row == selected_open_row);
    assign is_row_miss = selected_row_open_valid && (requested_row != selected_open_row);
    assign incoming_row_hit = incoming_row_open_valid && (decoded_req.row[ROW_WIDTH-1:0] == incoming_open_row);
    assign downstream_cmd_ready = ~service_pending_q;
    assign scheduler_timing_ok = is_row_hit || slow_path_allowed;
    assign incoming_timing_ok = incoming_row_hit || slow_path_allowed;
    assign controller_ready = downstream_cmd_ready && scheduler_timing_ok;
    assign cmd_ready = downstream_cmd_ready && incoming_timing_ok;
    assign txn_sched_grant = ~ref_req;
    assign accept_txn_fire = issue_valid && controller_ready && txn_sched_grant;
    assign deq_en = accept_txn_fire;
    assign enqueue_req_valid = txn_valid && !txn_enqueued_q;
    assign enqueue_fire = enqueue_req_valid && enq_ready;
    assign accept_txn = accept_txn_q;
    assign accepted_hit = accept_txn_fire && is_row_hit;
    assign accepted_slow = accept_txn_fire && ~is_row_hit;
    assign accepted_read = accept_txn_fire && ~selected_req.is_write;
    assign accepted_write = accept_txn_fire && selected_req.is_write;
    assign service_done = service_pending_q && (service_cycles_left_q == SERVICE_COUNTER_WIDTH'(0));
    assign row_replacement_event = service_done && service_update_open_row_q && service_prev_row_valid_q;
    assign rsp_valid = rsp_valid_q;
    assign rsp_rdata = rsp_rdata_q;

    always_comb begin
        selected_row_open_valid = 1'b0;
        selected_open_row = '0;
        unique case (selected_bank)
            2'd0: begin
                selected_row_open_valid = row_open_valid[0];
                selected_open_row = open_row[0];
            end
            2'd1: begin
                selected_row_open_valid = row_open_valid[1];
                selected_open_row = open_row[1];
            end
            2'd2: begin
                selected_row_open_valid = row_open_valid[2];
                selected_open_row = open_row[2];
            end
            2'd3: begin
                selected_row_open_valid = row_open_valid[3];
                selected_open_row = open_row[3];
            end
            default: begin
                selected_row_open_valid = 1'b0;
                selected_open_row = '0;
            end
        endcase
    end

    always_comb begin
        incoming_row_open_valid = 1'b0;
        incoming_open_row = '0;
        unique case (incoming_bank)
            2'd0: begin
                incoming_row_open_valid = row_open_valid[0];
                incoming_open_row = open_row[0];
            end
            2'd1: begin
                incoming_row_open_valid = row_open_valid[1];
                incoming_open_row = open_row[1];
            end
            2'd2: begin
                incoming_row_open_valid = row_open_valid[2];
                incoming_open_row = open_row[2];
            end
            2'd3: begin
                incoming_row_open_valid = row_open_valid[3];
                incoming_open_row = open_row[3];
            end
            default: begin
                incoming_row_open_valid = 1'b0;
                incoming_open_row = '0;
            end
        endcase
    end
    assign scheduler_bank_active[0] = row_open_valid[0];
    assign scheduler_bank_open_row[0] = 10'(open_row[0]);
    assign scheduler_bank_open_row_packed[0*10 +: 10] = scheduler_bank_open_row[0];
    assign req_array[0] = request_t'(req_array_packed[0*51 +: 51]);
    assign req_valid[0] = req_valid_packed[0];
    assign scheduler_bank_active[1] = row_open_valid[1];
    assign scheduler_bank_open_row[1] = 10'(open_row[1]);
    assign scheduler_bank_open_row_packed[1*10 +: 10] = scheduler_bank_open_row[1];
    assign req_array[1] = request_t'(req_array_packed[1*51 +: 51]);
    assign req_valid[1] = req_valid_packed[1];
    assign scheduler_bank_active[2] = row_open_valid[2];
    assign scheduler_bank_open_row[2] = 10'(open_row[2]);
    assign scheduler_bank_open_row_packed[2*10 +: 10] = scheduler_bank_open_row[2];
    assign req_array[2] = request_t'(req_array_packed[2*51 +: 51]);
    assign req_valid[2] = req_valid_packed[2];
    assign scheduler_bank_active[3] = row_open_valid[3];
    assign scheduler_bank_open_row[3] = 10'(open_row[3]);
    assign scheduler_bank_open_row_packed[3*10 +: 10] = scheduler_bank_open_row[3];
    assign req_array[3] = request_t'(req_array_packed[3*51 +: 51]);
    assign req_valid[3] = req_valid_packed[3];
    assign bank_cmd_valid[0] = accepted_slow && (selected_bank[BANK_SEL_WIDTH-1:0] == 2'd0);
    assign bank0_cmd_type = bank_cmd_valid[0] ? txn_cmd_type : 2'b00;
    assign bank_cmd_valid[1] = accepted_slow && (selected_bank[BANK_SEL_WIDTH-1:0] == 2'd1);
    assign bank1_cmd_type = bank_cmd_valid[1] ? txn_cmd_type : 2'b00;
    assign bank_cmd_valid[2] = accepted_slow && (selected_bank[BANK_SEL_WIDTH-1:0] == 2'd2);
    assign bank2_cmd_type = bank_cmd_valid[2] ? txn_cmd_type : 2'b00;
    assign bank_cmd_valid[3] = accepted_slow && (selected_bank[BANK_SEL_WIDTH-1:0] == 2'd3);
    assign bank3_cmd_type = bank_cmd_valid[3] ? txn_cmd_type : 2'b00;
    assign act_pulse = |bank_cmd_valid;
    assign ref_ack = issue_ref;

    always_ff @(posedge clk) begin
        if (!rst_n) begin
            accept_txn_q <= 1'b0;
            txn_enqueued_q <= 1'b0;
            accepted_row_closed_q <= 1'b0;
            accepted_row_hit_q <= 1'b0;
            accepted_row_miss_q <= 1'b0;
            accepted_bank_q <= '0;
            accepted_txn_cmd_type_q <= 2'b00;
            accepted_bank_cmd_valid_q <= '0;
            accepted_open_row_valid_q <= 1'b0;
            accepted_prev_open_row_q <= '0;
            accepted_requested_row_q <= '0;
            accepted_requested_col_q <= '0;
            rsp_valid_q <= 1'b0;
            rsp_rdata_q <= '0;
            cnt_accept <= '0;
            cnt_row_hit <= '0;
            cnt_row_miss <= '0;
            cnt_row_closed <= '0;
            cnt_stall <= '0;
            cnt_stall_busy <= '0;
            cnt_stall_trrd <= '0;
            cnt_stall_refresh <= '0;
            cnt_stall_other <= '0;
            cnt_latency_hit_total <= '0;
            cnt_latency_nonhit_total <= '0;
            cnt_latency_hit_count <= '0;
            cnt_latency_nonhit_count <= '0;
            service_pending_q <= 1'b0;
            service_is_write_q <= 1'b0;
            service_update_open_row_q <= 1'b0;
            service_prev_row_valid_q <= 1'b0;
            service_bank_q <= '0;
            service_addr_q <= '0;
            service_wdata_q <= '0;
            service_row_q <= '0;
            service_prev_row_q <= '0;
            service_cycles_left_q <= '0;
            row_open_valid <= '0;
            for (bank_mem_bank = 0; bank_mem_bank < BANK_COUNT; bank_mem_bank = bank_mem_bank + 1) begin
                cnt_accept_bank[bank_mem_bank] <= '0;
                cnt_row_hit_bank[bank_mem_bank] <= '0;
                cnt_row_miss_bank[bank_mem_bank] <= '0;
                cnt_row_closed_bank[bank_mem_bank] <= '0;
                open_row[bank_mem_bank] <= '0;
                for (bank_mem_addr = 0; bank_mem_addr < MEM_DEPTH; bank_mem_addr = bank_mem_addr + 1) begin
                    bank_mem[bank_mem_bank][bank_mem_addr] <= '0;
                end
            end
        end else begin
            rsp_valid_q <= 1'b0;
            if (!txn_valid) begin
                txn_enqueued_q <= 1'b0;
            end else if (enqueue_fire) begin
                txn_enqueued_q <= 1'b1;
            end
            if (txn_valid && !cmd_ready) begin
                cnt_stall <= cnt_stall + 32'd1;
                if (service_pending_q) begin
                    cnt_stall_busy <= cnt_stall_busy + 32'd1;
                end else if (tRRD_block && !is_row_hit) begin
                    cnt_stall_trrd <= cnt_stall_trrd + 32'd1;
                end else if (!txn_sched_grant) begin
                    cnt_stall_refresh <= cnt_stall_refresh + 32'd1;
                end else begin
                    cnt_stall_other <= cnt_stall_other + 32'd1;
                end
            end
            if (service_pending_q) begin
                if (service_cycles_left_q != SERVICE_COUNTER_WIDTH'(0)) begin
                    service_cycles_left_q <= service_cycles_left_q - SERVICE_COUNTER_WIDTH'(1);
                end else begin
                    service_pending_q <= 1'b0;
                    if (service_update_open_row_q) begin
                        cnt_latency_nonhit_total <= cnt_latency_nonhit_total + SLOW_SERVICE_CYCLES;
                        cnt_latency_nonhit_count <= cnt_latency_nonhit_count + 32'd1;
                    end else begin
                        cnt_latency_hit_total <= cnt_latency_hit_total + HIT_SERVICE_CYCLES;
                        cnt_latency_hit_count <= cnt_latency_hit_count + 32'd1;
                    end
                    if (KEEP_ROWS_OPEN && service_update_open_row_q) begin
                        row_open_valid[service_bank_q] <= 1'b1;
                        open_row[service_bank_q] <= service_row_q;
                    end else if (!KEEP_ROWS_OPEN) begin
                        row_open_valid[service_bank_q] <= 1'b0;
                        open_row[service_bank_q] <= '0;
                    end
                    if (service_is_write_q) begin
                        bank_mem[service_bank_q][service_addr_q] <= service_wdata_q;
                    end else begin
                        rsp_valid_q <= 1'b1;
                        rsp_rdata_q <= bank_mem[service_bank_q][service_addr_q];
                    end
                end
            end
            accept_txn_q <= 1'b0;
            if (!service_pending_q && accept_txn_fire) begin
                accept_txn_q <= 1'b1;
                accepted_row_closed_q <= is_row_closed;
                accepted_row_hit_q <= is_row_hit;
                accepted_row_miss_q <= is_row_miss;
                accepted_bank_q <= selected_bank[BANK_SEL_WIDTH-1:0];
                accepted_txn_cmd_type_q <= txn_cmd_type;
                accepted_bank_cmd_valid_q <= '0;
                accepted_open_row_valid_q <= selected_row_open_valid;
                accepted_prev_open_row_q <= selected_open_row;
                accepted_requested_row_q <= requested_row;
                accepted_requested_col_q <= requested_col;
                cnt_accept <= cnt_accept + 32'd1;
                cnt_accept_bank[selected_bank[BANK_SEL_WIDTH-1:0]] <= cnt_accept_bank[selected_bank[BANK_SEL_WIDTH-1:0]] + 32'd1;
                if (is_row_hit) begin
                    cnt_row_hit <= cnt_row_hit + 32'd1;
                    cnt_row_hit_bank[selected_bank[BANK_SEL_WIDTH-1:0]] <= cnt_row_hit_bank[selected_bank[BANK_SEL_WIDTH-1:0]] + 32'd1;
                end else if (is_row_miss) begin
                    cnt_row_miss <= cnt_row_miss + 32'd1;
                    cnt_row_miss_bank[selected_bank[BANK_SEL_WIDTH-1:0]] <= cnt_row_miss_bank[selected_bank[BANK_SEL_WIDTH-1:0]] + 32'd1;
                end else if (is_row_closed) begin
                    cnt_row_closed <= cnt_row_closed + 32'd1;
                    cnt_row_closed_bank[selected_bank[BANK_SEL_WIDTH-1:0]] <= cnt_row_closed_bank[selected_bank[BANK_SEL_WIDTH-1:0]] + 32'd1;
                end
                if (!is_row_hit) begin
                    accepted_bank_cmd_valid_q[selected_bank[BANK_SEL_WIDTH-1:0]] <= 1'b1;
                end
                service_pending_q <= 1'b1;
                service_is_write_q <= selected_req.is_write;
                service_update_open_row_q <= accepted_slow;
                service_prev_row_valid_q <= selected_row_open_valid;
                service_bank_q <= selected_bank[BANK_SEL_WIDTH-1:0];
                service_addr_q <= selected_addr;
                service_wdata_q <= selected_req.wdata;
                service_row_q <= requested_row;
                service_prev_row_q <= selected_open_row;
                if (accepted_hit) begin
                    service_cycles_left_q <= SERVICE_COUNTER_WIDTH'(HIT_SERVICE_CYCLES - 1);
                end else begin
                    service_cycles_left_q <= SERVICE_COUNTER_WIDTH'(SLOW_SERVICE_CYCLES - 1);
                end
            end
        end
    end

    ddr4_request_queue #(.DEPTH(REQ_QUEUE_DEPTH)) u_request_queue (
        .clk(clk),
        .rst_n(rst_n),
        .enq_valid(enqueue_req_valid),
        .enq_req(decoded_req_packed),
        .enq_ready(enq_ready),
        .req_array(req_array_packed),
        .req_valid(req_valid_packed),
        .sel_idx(sel_idx),
        .deq_en(deq_en)
    );

    ddr4_scheduler_scheduler u_scheduler (
        .clk(clk),
        .rst_n(rst_n),
        .ref_req(ref_req),
        .bank_active(scheduler_bank_active),
        .bank_open_row(scheduler_bank_open_row_packed),
        .req_array(req_array_packed),
        .req_valid(req_valid_packed),
        .cmd_ready(downstream_cmd_ready),
        .timing_ok(ref_req ? slow_path_allowed : scheduler_timing_ok),
        .sel_idx(sel_idx),
        .issue_valid(issue_valid),
        .issue_ref(issue_ref),
        .issue_txn(issue_txn)
    );

    ddr4_bank_top u_bank0 (
        .clk(clk),
        .rst_n(rst_n),
        .cmd_valid(bank_cmd_valid[0]),
        .cmd_type(bank0_cmd_type),
        .bank_idle(bank_bank_idle[0]),
        .bank_active(bank_bank_active[0]),
        .cmd_ready(bank_cmd_ready[0]),
        .activating(bank_activating[0])
    );

    ddr4_bank_top u_bank1 (
        .clk(clk),
        .rst_n(rst_n),
        .cmd_valid(bank_cmd_valid[1]),
        .cmd_type(bank1_cmd_type),
        .bank_idle(bank_bank_idle[1]),
        .bank_active(bank_bank_active[1]),
        .cmd_ready(bank_cmd_ready[1]),
        .activating(bank_activating[1])
    );

    ddr4_bank_top u_bank2 (
        .clk(clk),
        .rst_n(rst_n),
        .cmd_valid(bank_cmd_valid[2]),
        .cmd_type(bank2_cmd_type),
        .bank_idle(bank_bank_idle[2]),
        .bank_active(bank_bank_active[2]),
        .cmd_ready(bank_cmd_ready[2]),
        .activating(bank_activating[2])
    );

    ddr4_bank_top u_bank3 (
        .clk(clk),
        .rst_n(rst_n),
        .cmd_valid(bank_cmd_valid[3]),
        .cmd_type(bank3_cmd_type),
        .bank_idle(bank_bank_idle[3]),
        .bank_active(bank_bank_active[3]),
        .cmd_ready(bank_cmd_ready[3]),
        .activating(bank_activating[3])
    );

    ddr4_refresh_refresh_controller u_refresh_controller (
        .clk(clk),
        .rst_n(rst_n),
        .ref_ack(ref_ack),
        .ref_req(ref_req)
    );

    ddr4_tFAW_tFAW_tracker u_tFAW_tracker (
        .clk(clk),
        .rst_n(rst_n),
        .act_pulse(act_pulse),
        .act_count(tFAW_act_count),
        .tFAW_block(tFAW_block),
        .tFAW_ok(tFAW_ok)
    );

    ddr4_tRRD_simple_tRRD u_tRRD (
        .clk(clk),
        .rst_n(rst_n),
        .act_pulse(act_pulse),
        .tRRD_block(tRRD_block)
    );

endmodule  // ddr4_controller_top
