`timescale 1ns/1ps
// ============================================================
// Auto-generated by fsm_generator.py -- DO NOT EDIT
// Design : ddr4_bank_bank_sequencer
// States : IDLE, ACTIVATING, ACTIVE, PRECHARGING
// Reset  : rst_n (sync)
// Regenerate: python3 fsm_generator.py <spec>.yaml
// ============================================================

module ddr4_bank_bank_sequencer (
    input  logic        clk,
    input  logic        rst_n,
    input  logic        cmd_valid,
    input  logic [ 1:0] cmd_type,
    input  logic        tRCD_done,
    input  logic        tRAS_done,
    input  logic        tRP_done,
    output logic        bank_idle,
    output logic        bank_active,
    output logic        cmd_ready,
    output logic        tRCD_start,
    output logic        tRAS_start,
    output logic        tRP_start,
    output logic        tRCD_ack,
    output logic        tRAS_ack,
    output logic        tRP_ack
);

    // ---------------------------------------------------------
    // State type
    // ---------------------------------------------------------
    typedef enum logic [1:0] {
        IDLE                 = 2'd0,
        ACTIVATING           = 2'd1,
        ACTIVE               = 2'd2,
        PRECHARGING          = 2'd3
    } state_t;

    state_t current_state, next_state;

    // ---------------------------------------------------------
    // State register  (sync reset)
    // ---------------------------------------------------------
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            current_state <= IDLE;
        end else begin
            current_state <= next_state;
        end
    end

    // ---------------------------------------------------------
    // Next-state logic
    // ---------------------------------------------------------
    always_comb begin
        next_state = current_state;  // default: hold current state
        case (current_state)
            IDLE: if (cmd_valid == 1'd1 && cmd_ready == 1'd1) next_state = ACTIVATING;
            ACTIVATING: if (tRCD_done == 1'd1) next_state = ACTIVE;
            ACTIVE: if (tRAS_done == 1'd1) next_state = PRECHARGING;
            PRECHARGING: if (tRP_done == 1'd1) next_state = IDLE;
            default: next_state = IDLE;  // illegal encoding -- recover to reset state
        endcase
    end

    // ---------------------------------------------------------
    // Output logic (Moore)
    // ---------------------------------------------------------
    always_comb begin
        bank_idle = (current_state == IDLE);
        bank_active = (current_state == ACTIVE);
        cmd_ready = (current_state == IDLE);
        tRCD_start = (current_state == ACTIVATING);
        tRAS_start = (current_state == ACTIVE);
        tRP_start = (current_state == PRECHARGING);
        tRCD_ack = (current_state == ACTIVE);
        tRAS_ack = (current_state == PRECHARGING);
        tRP_ack = (current_state == IDLE);
    end

endmodule  // ddr4_bank_bank_sequencer
