`timescale 1ns/1ps
// ============================================================
// Auto-generated by fsm_generator.py -- DO NOT EDIT
// Design : ddr4_refresh_refresh_controller
// States : IDLE, REQUEST
// Reset  : rst_n (sync)
// Regenerate: python3 fsm_generator.py <spec>.yaml
// ============================================================

module ddr4_refresh_refresh_controller (
    input  logic        clk,
    input  logic        rst_n,
    input  logic        ref_ack,
    output logic        ref_req
);

    // ---------------------------------------------------------
    // State type
    // ---------------------------------------------------------
    typedef enum logic [0:0] {
        IDLE                 = 1'd0,
        REQUEST              = 1'd1
    } state_t;

    state_t current_state, next_state;

    // ---------------------------------------------------------
    // Counters (auto-sized from transition conditions)
    // ---------------------------------------------------------
    logic [13:0] counter;  // 14 bit(s), holds up to 16383
    localparam int COUNTER_WIDTH = $bits(counter);
    localparam logic [COUNTER_WIDTH-1:0] COUNTER_ZERO_L = COUNTER_WIDTH'(0);
    localparam logic [COUNTER_WIDTH-1:0] COUNTER_ONE_L = COUNTER_WIDTH'(1);

    // ---------------------------------------------------------
    // State register  (sync reset)
    // ---------------------------------------------------------
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            current_state <= IDLE;
            counter <= COUNTER_ZERO_L;
        end else begin
            current_state <= next_state;
            // Reset counters on any state change;
            // increment only in the state the counter belongs to.
            if (current_state != next_state) begin
                counter <= COUNTER_ZERO_L;
            end else begin
                if (current_state == IDLE) begin
                    counter <= counter + COUNTER_ONE_L;
                end
            end
        end
    end

    // ---------------------------------------------------------
    // Next-state logic
    // ---------------------------------------------------------
    always_comb begin
        next_state = current_state;  // default: hold current state
        case (current_state)
            IDLE: if (counter >= 14'd12480) next_state = REQUEST;
            REQUEST: if (ref_ack == 1'd1) next_state = IDLE;
            default: next_state = IDLE;  // illegal encoding -- recover to reset state
        endcase
    end

    // ---------------------------------------------------------
    // Output logic (Moore)
    // ---------------------------------------------------------
    always_comb begin
        ref_req = (current_state == REQUEST);
    end

endmodule  // ddr4_refresh_refresh_controller
