`timescale 1ns/1ps
// ============================================================
// Auto-generated by generate_wrapper.py -- DO NOT EDIT
// Design : ddr4_bank_top
// Purpose: Package the per-bank FSM chain behind one reusable module
// ============================================================

module ddr4_bank_top (
    input  logic       clk,
    input  logic       rst_n,
    input  logic       cmd_valid,
    input  logic [1:0] cmd_type,
    output logic       bank_idle,
    output logic       bank_active,
    output logic       cmd_ready,
    output logic       activating
);

    logic tRCD_start;
    logic tRAS_start;
    logic tRP_start;
    logic tRCD_done;
    logic tRAS_done;
    logic tRP_done;
    logic tRCD_ack;
    logic tRAS_ack;
    logic tRP_ack;

    assign activating = tRCD_start;

    ddr4_bank_bank_sequencer u_bank_sequencer (
        .clk(clk),
        .rst_n(rst_n),
        .cmd_valid(cmd_valid),
        .cmd_type(cmd_type),
        .tRCD_done(tRCD_done),
        .tRAS_done(tRAS_done),
        .tRP_done(tRP_done),
        .bank_idle(bank_idle),
        .bank_active(bank_active),
        .cmd_ready(cmd_ready),
        .tRCD_start(tRCD_start),
        .tRAS_start(tRAS_start),
        .tRP_start(tRP_start),
        .tRCD_ack(tRCD_ack),
        .tRAS_ack(tRAS_ack),
        .tRP_ack(tRP_ack)
    );

    ddr4_bank_activate_fsm u_activate_fsm (
        .clk(clk),
        .rst_n(rst_n),
        .start(tRCD_start),
        .ack(tRCD_ack),
        .tRCD_done(tRCD_done)
    );

    ddr4_bank_tRAS_fsm u_tRAS_fsm (
        .clk(clk),
        .rst_n(rst_n),
        .start(tRAS_start),
        .ack(tRAS_ack),
        .tRAS_done(tRAS_done)
    );

    ddr4_bank_precharge_fsm u_precharge_fsm (
        .clk(clk),
        .rst_n(rst_n),
        .start(tRP_start),
        .ack(tRP_ack),
        .tRP_done(tRP_done)
    );

endmodule  // ddr4_bank_top
