#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
DRY_RUN=0

usage() {
    cat <<'EOF'
Usage: ./clear.sh [--dry-run]

Removes artifacts generated by:
  - ./start_flow.sh
  - ./run_sim.sh
  - python3 debug_agent.py ... debug/demo flows

Preserves source inputs, configs/user_input.yaml, jedec/, debug fixtures, and
debug layout .gitkeep files.

This includes generated RTL (and manual edits there), testbenches, the LLM
cache, and numbered debug workspaces with their patches and checkpoints.
Use --dry-run to preview the exact paths without deleting anything.
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --dry-run)
            DRY_RUN=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown flag: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

display_path() {
    local path="$1"
    printf '%s\n' "${path#$SCRIPT_DIR/}"
}

require_repo_path() {
    local path="$1"
    case "$path" in
        "$SCRIPT_DIR"/*)
            ;;
        *)
            echo "[CLEAR] Refusing path outside repo: $path" >&2
            exit 1
            ;;
    esac
    # rm does not follow a final symlink, but it traverses symlinked parents.
    local parent="${path%/*}"
    while [ "$parent" != "$SCRIPT_DIR" ]; do
        if [ -L "$parent" ]; then
            echo "[CLEAR] Refusing symlinked parent: $parent" >&2
            exit 1
        fi
        parent="${parent%/*}"
    done
}

remove_path() {
    local path="$1"
    require_repo_path "$path"

    if [ ! -e "$path" ] && [ ! -L "$path" ]; then
        echo "[CLEAR] skip missing: $(display_path "$path")"
        return 0
    fi

    if [ "$DRY_RUN" -eq 1 ]; then
        local suffix=""
        if [ -d "$path" ] && [ ! -L "$path" ]; then
            suffix="/"
        fi
        echo "[CLEAR] would remove: $(display_path "$path")$suffix"
        return 0
    fi

    rm -rf -- "$path"
    echo "[CLEAR] removed: $(display_path "$path")"
}

collect_matches() {
    local label="$1"
    shift

    if [ "$#" -eq 0 ]; then
        echo "[CLEAR] skip missing: $label"
        return 0
    fi

    local path
    for path in "$@"; do
        targets+=("$path")
    done
}

generated_dirs=(
    "$SCRIPT_DIR/rtl_output"
    "$SCRIPT_DIR/expanded"
    "$SCRIPT_DIR/inputs/generated"
    "$SCRIPT_DIR/tb"
    "$SCRIPT_DIR/obj_dir"
    "$SCRIPT_DIR/__pycache__"
    "$SCRIPT_DIR/.llm_cache"
)

generated_files=(
    "$SCRIPT_DIR/flow.log"
    "$SCRIPT_DIR/flow_lint.log"
    "$SCRIPT_DIR/bist.log"
)

targets=("${generated_dirs[@]}" "${generated_files[@]}")

collect_matches "ir/*_ir.json" "$SCRIPT_DIR"/ir/*_ir.json
collect_matches "*.vcd" "$SCRIPT_DIR"/*.vcd
collect_matches "*.fst" "$SCRIPT_DIR"/*.fst
for path in "$SCRIPT_DIR"/debug/failures/[0-9]*_*; do
    if [[ "${path##*/}" =~ ^[0-9]{4,}_.+$ ]] && { [ -d "$path" ] || [ -L "$path" ]; }; then
        targets+=("$path")
    fi
done

# Validate every target before deleting anything, including paths with no matches.
for path in "${targets[@]}" "$SCRIPT_DIR/ir/_probe" "$SCRIPT_DIR/debug/failures/_probe"; do
    require_repo_path "$path"
done
for path in "${targets[@]}"; do
    remove_path "$path"
done

echo "[CLEAR] Done."
