design_name: ddr4_controller
profile:
  type: basic
memory:
  protocol: DDR4
  speed: '2400'
topology:
  banks: 1
features:
  scheduler: simple
  page_policy: close_page
  refresh: true
  tFAW: false
  tRRD: false
